apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash.fullname" . }}
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
data:
  logstash.yml: |
    api.http.host: 0.0.0.0
  pipelines.yml: |
    - pipeline.id: bank-logs
      path.config: /usr/share/logstash/pipeline/bank.conf
  bank.conf: |
    input {
      tcp {
        port => {{ .Values.service.tcpPort }}
        codec => json_lines
      }
    }
    filter {
      mutate {
        add_field => { "environment" => "dev" }
        remove_field => [ "password", "token", "authorization", "client_secret" ]
        replace => {
          "account" => "***"
          "account_number" => "***"
          "accountNumber" => "***"
        }
      }
    }
    output {
      elasticsearch {
        hosts => [ "{{ .Values.config.elasticsearchUrl }}" ]
        index => "bank-logs-%{+YYYY.MM.dd}"
      }
    }
