node {
    checkout scm
    load('ci/jenkins-service.groovy').runServicePipeline(
        serviceName: 'front-ui',
        gradleModule: ':front-ui',
        chartPath: 'helm/charts/front-ui',
        imageRepository: 'my-bank-front-ui'
    )
}
