global:
  namespace: prod
  publicBaseUrl: https://bank.example.local
  imageTag: stable
  keycloakPublicUrl: https://bank.example.local/realms/bank-realm
  env:
    BANK_KEYCLOAK_ISSUER_URI: https://bank.example.local/realms/bank-realm

gatewayApi:
  listener:
    hostname: bank.example.local

front-ui:
  env:
    BANK_KEYCLOAK_AUTHORIZATION_URI: https://bank.example.local/realms/bank-realm/protocol/openid-connect/auth
    BANK_KEYCLOAK_END_SESSION_URI: https://bank.example.local/realms/bank-realm/protocol/openid-connect/logout
    BANK_KEYCLOAK_REDIRECT_URI: https://bank.example.local/login/oauth2/code/{registrationId}

keycloak:
  extraEnv:
    - name: KC_HOSTNAME
      value: https://bank.example.local
    - name: KC_HOSTNAME_STRICT
      value: "false"
  realmImport:
    frontUiPublicUrl: https://bank.example.local
