global:
  namespace: test
  publicBaseUrl: https://bank-test.example.local
  imageTag: test
  keycloakPublicUrl: https://bank-test.example.local/realms/bank-realm
  env:
    BANK_KEYCLOAK_ISSUER_URI: https://bank-test.example.local/realms/bank-realm

gatewayApi:
  listener:
    hostname: bank-test.example.local

kafka:
  clusterId: oFd3r3FUc7MK006D_mS9oA

elasticsearch:
  enabled: false

logstash:
  enabled: false

kibana:
  enabled: false

front-ui:
  env:
    BANK_KEYCLOAK_AUTHORIZATION_URI: https://bank-test.example.local/realms/bank-realm/protocol/openid-connect/auth
    BANK_KEYCLOAK_END_SESSION_URI: https://bank-test.example.local/realms/bank-realm/protocol/openid-connect/logout
    BANK_KEYCLOAK_REDIRECT_URI: https://bank-test.example.local/login/oauth2/code/{registrationId}

keycloak:
  extraEnv:
    - name: KC_HOSTNAME
      value: https://bank-test.example.local
    - name: KC_HOSTNAME_STRICT
      value: "false"
  realmImport:
    frontUiPublicUrl: https://bank-test.example.local
