spring:
  application:
    name: exchange-service
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BANK_KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/bank-realm}
          jwk-set-uri: ${BANK_KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/bank-realm/protocol/openid-connect/certs}

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8096}
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  metrics:
    tags:
      application: ${spring.application.name}
      namespace: ${MANAGEMENT_METRICS_TAGS_NAMESPACE:dev}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

server:
  port: 8086
