replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: 26.6.3
  pullPolicy: IfNotPresent

service:
  port: 8080

admin:
  existingSecret: keycloak-credentials
  usernameKey: admin-username
  passwordKey: admin-password

realmImport:
  enabled: true
  createSecret: true
  existingSecret: keycloak-realm
  key: bank-realm.json
  file: files/bank-realm.json
  frontUiPublicUrl: http://localhost
  secretEnv:
    - name: FRONT_UI_CLIENT_SECRET
      secretName: bank-service-credentials
      key: FRONT_UI_CLIENT_SECRET
    - name: CASH_SERVICE_CLIENT_SECRET
      secretName: bank-service-credentials
      key: CASH_SERVICE_CLIENT_SECRET
    - name: TRANSFER_SERVICE_CLIENT_SECRET
      secretName: bank-service-credentials
      key: TRANSFER_SERVICE_CLIENT_SECRET
    - name: EXCHANGE_GENERATOR_CLIENT_SECRET
      secretName: bank-service-credentials
      key: EXCHANGE_GENERATOR_CLIENT_SECRET

extraEnv: []

resources: {}
