server:
  port: 8082

spring:
  application:
    name: cash-service

bank:
  services:
    accounts:
      base-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
