[versions]
spring-boot = "3.5.15"
spring-cloud = "2025.0.2"
spring-dependency-management = "1.1.7"
spring-cloud-contract = "4.3.2"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spring-cloud-contract = { id = "org.springframework.cloud.contract", version.ref = "spring-cloud-contract" }

