node {
    checkout scm
    load('ci/jenkins-service.groovy').runServicePipeline(
        serviceName: 'bank-gateway',
        gradleModule: ':bank-gateway',
        chartPath: 'helm/charts/spring-service',
        valuesPath: 'helm/values/services/bank-gateway.yaml',
        imageRepository: 'my-bank-gateway'
    )
}
