fullnameOverride: accounts-service

image:
  repository: my-bank-accounts-service

service:
  port: 8081

management:
  enabled: true
  port: 8091

probes:
  port: management

env:
  MANAGEMENT_SERVER_PORT: "8091"
  MANAGEMENT_TRACING_PROPAGATION_TYPE: W3C
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
  MANAGEMENT_ZIPKIN_TRACING_EXPORT_ENABLED: "true"
