fullnameOverride: blocker-service

image:
  repository: my-bank-blocker-service

service:
  port: 8088

management:
  enabled: true
  port: 8098

probes:
  port: management

env:
  MANAGEMENT_SERVER_PORT: "8098"
