fullnameOverride: cash-service

image:
  repository: my-bank-cash-service

service:
  port: 8082

management:
  enabled: true
  port: 8092

probes:
  port: management

env:
  MANAGEMENT_SERVER_PORT: "8092"
