fullnameOverride: exchange-generator

image:
  repository: my-bank-exchange-generator

service:
  port: 8087

management:
  enabled: true
  port: 8097

probes:
  port: management

env:
  MANAGEMENT_SERVER_PORT: "8097"
  MANAGEMENT_TRACING_PROPAGATION_TYPE: W3C
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
  MANAGEMENT_ZIPKIN_TRACING_EXPORT_ENABLED: "true"
