fullnameOverride: exchange-service

image:
  repository: my-bank-exchange-service

service:
  port: 8086

management:
  enabled: true
  port: 8096

probes:
  port: management

env:
  MANAGEMENT_SERVER_PORT: "8096"
  MANAGEMENT_TRACING_PROPAGATION_TYPE: W3C
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
  MANAGEMENT_ZIPKIN_TRACING_EXPORT_ENABLED: "true"
