node {
    checkout scm
    load('ci/jenkins-service.groovy').runServicePipeline(
        serviceName: 'cash-service',
        gradleModule: ':cash-service',
        chartPath: 'helm/charts/spring-service',
        valuesPath: 'helm/values/services/cash-service.yaml',
        imageRepository: 'my-bank-cash-service'
    )
}
