node {
    checkout scm
    load('ci/jenkins-service.groovy').runServicePipeline(
        serviceName: 'transfer-service',
        gradleModule: ':transfer-service',
        chartPath: 'helm/charts/transfer-service',
        imageRepository: 'my-bank-transfer-service'
    )
}
