spring:
  application:
    name: notifications-service
  main:
    web-application-type: none
  jackson:
    default-property-inclusion: non_null
  kafka:
    admin:
      fail-fast: true
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:bank-notifications}
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: ru.practicum.bank.common.notification.NotificationEvent
        spring.json.trusted.packages: ru.practicum.bank.common.notification
    listener:
      ack-mode: record
bank:
  kafka:
    notifications-topic: ${BANK_KAFKA_NOTIFICATIONS_TOPIC:bank.notifications}
    notifications-dlt-topic: ${BANK_KAFKA_NOTIFICATIONS_DLT_TOPIC:bank.notifications.dlt}
