server:
  port: 8080

spring:
  application:
    name: bank-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: block-accounts-internal-api
              uri: no://op
              predicates:
                - Path=/api/accounts/internal/**
              filters:
                - SetStatus=404
            - id: accounts-service
              uri: lb://accounts-service
              predicates:
                - Path=/api/accounts/**
            - id: cash-service
              uri: lb://cash-service
              predicates:
                - Path=/api/cash/**
            - id: transfer-service
              uri: lb://transfer-service
              predicates:
                - Path=/api/transfers/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bank-realm

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
