{{- if and .Values.realmImport.enabled .Values.realmImport.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "realmImport.existingSecret is required" .Values.realmImport.existingSecret }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ required "realmImport.key is required" .Values.realmImport.key }}: |-
{{ .Files.Get (required "realmImport.file is required" .Values.realmImport.file) | nindent 4 }}
{{- end }}
