spring:
  application:
    name: accounts-service
  datasource:
    url: ${BANK_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${BANK_DATASOURCE_USERNAME:postgres}
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BANK_KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/bank-realm}
          jwk-set-uri: ${BANK_KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/bank-realm/protocol/openid-connect/certs}

bank:
  kafka:
    notifications-topic: ${BANK_KAFKA_NOTIFICATIONS_TOPIC:bank.notifications}

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8081
