node {
    checkout scm
    load('ci/jenkins-service.groovy').runServicePipeline(
        serviceName: 'blocker-service',
        gradleModule: ':blocker-service',
        chartPath: 'helm/charts/blocker-service',
        imageRepository: 'my-bank-blocker-service'
    )
}
