spring:
  application:
    name: accounts-service
  datasource:
    url: ${BANK_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${BANK_DATASOURCE_USERNAME:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BANK_KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/bank-realm}
          jwk-set-uri: ${BANK_KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/bank-realm/protocol/openid-connect/certs}

server:
  port: 8081
