node {
    checkout scm
    load('ci/jenkins-service.groovy').runServicePipeline(
        serviceName: 'notifications-service',
        gradleModule: ':notifications-service',
        chartPath: 'helm/charts/notifications-service',
        imageRepository: 'my-bank-notifications-service'
    )
}
